# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: vanbitcase
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: djangologin
service: django-app

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline
  - serverless-wsgi


functions:
  django:
    handler: wsgi.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

custom:
  wsgi:
    app: djangologin.wsgi.application  # Adjust to your Django project's WSGI application path
    pythonBin: python3
  serverless-offline:
    port: 3000
